name: DAST - ZAP (containers)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # sobe sua app como container na rede "zapnet"
      - name: Start app (docker compose)
        run: |
          docker network create zapnet || true
          docker compose up -d
          # sanity-check: aguarda a app responder
          for i in {1..30}; do
            if curl -fsS http://app:3000/ >/dev/null; then echo "UP"; break; fi
            sleep 2
          done

      # roda o ZAP na mesma network e acessa a app pelo hostname do serviço: http://app:3000
      - name: ZAP Baseline
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          docker_network: 'zapnet'
          target: 'http://app:3000'
          cmd_options: '-a'     # agressivo passivo
          allow_issue_writing: false
          artifact_name: 'zap-dast-report'

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            report_html.html
            zap.out
          retention-days: 14

      - name: Tear down
        if: always()
        run: docker compose down -v
