# .github/workflows/dast.yml
name: DAST - ZAP Baseline (localhost)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Start app with Compose
        run: |
          docker compose up -d
          # aguarda a app responder em localhost:3000
          for i in {1..30}; do
            if curl -fsS http://127.0.0.1:3000/ >/dev/null; then
              echo "APP UP"; break; fi
            sleep 2
          done

      - name: ZAP Baseline Scan (localhost)
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'http://127.0.0.1:3000'   # use localhost, não "app"
          cmd_options: '-a'
          allow_issue_writing: false
          artifact_name: 'zap-dast-report'

      - name: Tear down
        if: always()
        run: docker compose down -v
