name: DAST - ZAP (containers)

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  zap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # cria a rede externa uma vez (não falha se já existir)
      - name: Create external network
        run: docker network create zapnet || true

      - name: Start app on zapnet
        run: |
          docker compose up -d
          # aguarda a app responder dentro da rede
          for i in {1..30}; do
            if docker run --rm --network zapnet curlimages/curl:8.9.1 -fsS http://app:3000/ >/dev/null; then
              echo "APP UP"; break; fi
            sleep 2
          done

      - name: ZAP Baseline (same network)
        uses: zaproxy/action-baseline@v0.14.0
        with:
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          docker_network: 'zapnet'
          target: 'http://app:3000'
          cmd_options: '-a'
          allow_issue_writing: false
          artifact_name: 'zap-dast-report'

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            report_html.html
            zap.out
          retention-days: 14

      - name: Tear down
        if: always()
        run: docker compose down -v
