name: DAST - ZAP Baseline
on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]

jobs:
  zap-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: ${{ secrets.STAGING_URL }}   # defina em Settings > Secrets > Actions
          rules_file_name: ''
          cmd_options: '-a'                    # agressivo passivo
          allow_issue_writing: false

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            report_html.html
            zap.out
          retention-days: 14
