# .github/workflows/sca.yml
name: SCA - Dependency Check

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write   # necessário para enviar SARIF

jobs:
  dependency-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Cache do banco NVD para acelerar execuções futuras
      - name: Cache DC Data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dc-data-${{ runner.os }}-v8

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "${{ github.repository }}"
          path: "."                     # ajuste se quiser escanear subpastas específicas
          format: "ALL"                 # <-- CORRIGIDO (gera HTML, JSON, SARIF, etc.)
          out: "dc-reports"
          args: >
            --failOnCVSS 7.0
            --enableRetired
            --enableExperimental
            --disableArchive
            --scan ./
            --suppression sca/dependency-check-suppressions.xml

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: dc-reports/dependency-check-report.sarif

      - name: Upload SCA reports
        uses: actions/upload-artifact@v4
        with:
          name: sca-dependency-check-${{ github.run_attempt }}
          path: dc-reports/*
          retention-days: 14
          overwrite: true
