name: SCA - Dependency Check

on:
  workflow_dispatch:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read
  security-events: write

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node and install deps
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: npm ci (populate node_modules)
        run: |
          if [ -f package-lock.json ] || [ -f package.json ]; then
            npm ci || npm i
          fi

      - name: Cache DC Data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: dc-data-${{ runner.os }}-v8

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "${{ github.repository }}"
          path: "."
          format: "ALL"
          out: "dc-reports"
          args: >
            --failOnCVSS 7.0
            --enableRetired
            --enableExperimental
            --disableArchive
            --scan ./
            ${{ (secrets.OSSINDEX_USER != '' && secrets.OSSINDEX_TOKEN != '')
                && format('--ossIndexUsername {0} --ossIndexPassword {1}', secrets.OSSINDEX_USER, secrets.OSSINDEX_TOKEN)
                || '--disableOssIndex' }}

      - name: Upload SARIF to Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: dc-reports/dependency-check-report.sarif

      - name: Upload SCA reports
        uses: actions/upload-artifact@v4
        with:
          name: sca-dependency-check-${{ github.run_attempt }}
          path: dc-reports/*
          retention-days: 14
          overwrite: true
